[package]
name = "weltc"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.4"
html5ever = "0.25.1"

[dependencies.ra-syntax]
package = "syntax"
git = "https://github.com/rust-analyzer/rust-analyzer"
rev = "116c7aef7fad2835f127c8573543a05de8376978"
